version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '2565:2565'
    environment:
      DATABASE_URL: postgresql://root:root@db/expenses-db?sslmode=disable
      PORT: :2565
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: expenses-db
